spring:
  healthcheckEndpoint: /api/health
  replicas: 1
  docker:
    repository: gigabyteme
    image: iguana-service
    tag: 1.0.0-SNAPSHOT

mongo:
  dbname: iguana-db
  replicas: 1
  port: 27017
  docker:
    image: mongo
    # Version 5.0+ will break with older system architectures
    tag: 4.4.8