apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-iguana
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo-iguana

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-iguana
  labels:
    app: mongo-iguana
spec:
  selector:
    matchLabels:
      app: mongo-iguana
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-iguana

    spec:
      containers:
        - image: mongo:latest
          name: mongo-iguana
          imagePullPolicy: Always

          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc