spring:
  healthcheckEndpoint: /api/health
  replicas: 1
  docker:
    repository: gigabyteme
    image: iguana-service
    tag: 0.2.0-SNAPSHOT

mongo:
  dbname: iguana-anywhere
  replicas: 1
  port: 27017
  docker:
    image: mongo
    tag: latest