name: Iguana CI

on: [push, pull_request]

jobs:
  Build Pipeline:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Grant Execute Permission for gradlew
      run: chmod +x gradlew

    - name: Execute Unit Tests
      run: ./gradlew build

    - name: Docker Hub Login
      run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Create Application Docker Image
      run: docker build . -t $(./gradlew projectDockerImage)

    - name: Push Docker Image
      run: docker push $(./gradlew projectDockerImage)