name: Iguana CI

on: [push, pull_request]

jobs:
  Build Pipeline:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Grant Execute Permission for gradlew
      run: chmod +x gradlew

    - name: Execute Unit Tests
      run: ./gradlew build

    - name: Store Application Version
      run: echo '::set-output name=APP_VERSION::$(./gradlew getProjectVersion)'
      id: gradle-project

    - name: Build and Push Docker Image
      if: github.ref == 'refs/heads/main'
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker build . -t gigabyteme/iguana-service:${{ steps.gradle-project.output.APP_VERSION}}
        docker push gigabyteme/iguana-service:${{ steps.gradle-project.output.APP_VERSION}}
