name: Iguana CI

on: [push, pull_request]

jobs:
  test-pipeline:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Grant Execute Permission for gradlew
        run: chmod +x gradlew

      - name: Execute Unit Tests
        run: ./gradlew test